services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - ".env"
    command: >
       sh -c "python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    env_file:
      - ".env"

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A core.celery.app worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis
      - db
    env_file:
      - ".env"

  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A core.celery.app flower
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"

